spring.application.name=tintucTest
spring.datasource.url=jdbc:mysql://localhost:3306/QLTinTuc
spring.datasource.username=root
spring.datasource.password=tonphan495

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false