spring.application.name=springboot-ai-chatbot-test

spring.ai.openai.base-url=https://api.groq.com/openai

spring.ai.openai.api-key=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

spring.ai.openai.chat.options.model=llama-3.3-70b-versatile